/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 27794ac33efd3bc997f364af6e4d3136)
interface __BaseEnv_Env {
	GOLDSHORE_KV: KVNamespace;
	ENVIRONMENT: "remote" | "staging" | "production" | "local";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface RemoteEnv {
		GOLDSHORE_KV: KVNamespace;
		ENVIRONMENT: "remote";
	}
	interface StagingEnv {
		GOLDSHORE_KV: KVNamespace;
		ENVIRONMENT: "staging";
	}
	interface ProductionEnv {
		GOLDSHORE_KV: KVNamespace;
		ENVIRONMENT: "production";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
